version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: turnos_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: turnos_db
      MYSQL_USER: turnos_user
      MYSQL_PASSWORD: turnos_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: